name: Code Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: Python v${{ matrix.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Linting
        run: poetry run flake8 ./slimer

      - name: Formatting
        run: poetry run black --check ./slimer

      - name: Security Checks
        run: poetry run bandit -r ./slimer

      - name: Test Coverage
        run: poetry run pytest ./tests --cov=slimer

      - name: Build
        run: poetry build
